import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { Bell, BellOff, Store, Users } from 'lucide-react-native';
import ScreenHeader from '../src/components/ScreenHeader';
import EmptyState from '../src/components/EmptyState';
import apiClient from '../src/api/client';
import { ENDPOINTS } from '../src/api/endpoints';
import { resolveImg } from '../src/lib/media';
import { toast } from '../src/lib/toast';
import { invalidateCachedData } from '../src/lib/dataCache';
import { colors, fontFamily, radius, spacing, typography } from '../src/theme';

export default function FollowedStores() {
  const router = useRouter();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState(null);
  const fetchItems = useCallback(async () => { setLoading(true); try { const response = await apiClient.get(ENDPOINTS.FOLLOWS.MINE); setItems(response.data || []); } catch (error) { toast.error('Failed to load followed stores', error.message); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { fetchItems(); }, [fetchItems]));
  const unfollow = async (item) => { setBusyId(item.store.id); try { await apiClient.delete(ENDPOINTS.FOLLOWS.FOLLOW(item.store.id)); setItems((current) => current.filter((entry) => entry.store.id !== item.store.id)); invalidateCachedData('profile:'); toast.success(`Unfollowed ${item.store.name}`); } catch (error) { toast.error('Could not unfollow', error.message); } finally { setBusyId(null); } };
  const toggleNotifications = async (item) => { setBusyId(item.store.id); try { const response = await apiClient.patch(ENDPOINTS.FOLLOWS.NOTIFICATIONS(item.store.id), { enabled: !item.notificationsEnabled }); setItems((current) => current.map((entry) => entry.store.id === item.store.id ? { ...entry, notificationsEnabled: response.data.notificationsEnabled } : entry)); } catch (error) { toast.error('Could not update alerts', error.message); } finally { setBusyId(null); } };
  return <View style={styles.screen}><ScreenHeader title="Followed Stores" subtitle="Updates from local sellers" />{loading ? <View style={styles.center}><ActivityIndicator color={colors.primary} /></View> : <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} ListEmptyComponent={<EmptyState icon={<Store size={44} color={colors.gray400} />} title="No followed stores" message="Follow local shops to find their newest products faster." actionLabel="Discover stores" onAction={() => router.push('/stores')} />} renderItem={({ item }) => { const store = item.store; return <View style={styles.card}>{store.coverImage || store.bannerImage ? <Image source={{ uri: resolveImg(store.coverImage || store.bannerImage) }} style={styles.banner} /> : <View style={[styles.banner, styles.bannerFallback]} />}<View style={styles.body}><Pressable onPress={() => router.push(`/store/${store.slug}`)}><Text style={styles.name}>{store.name}</Text><Text style={styles.location}>{store.municipality?.name || 'Oriental Mindoro'}</Text></Pressable>{store.description ? <Text style={styles.description} numberOfLines={2}>{store.description}</Text> : null}<View style={styles.stats}><Store size={13} color={colors.textMuted} /><Text style={styles.stat}>{store.productCount || 0} products</Text><Users size={13} color={colors.textMuted} /><Text style={styles.stat}>{store.followerCount || 0} followers</Text></View><View style={styles.actions}><Pressable style={styles.iconButton} disabled={busyId === store.id} onPress={() => toggleNotifications(item)}>{item.notificationsEnabled ? <Bell size={17} color={colors.secondary} /> : <BellOff size={17} color={colors.textMuted} />}</Pressable><Pressable style={styles.viewButton} onPress={() => router.push(`/store/${store.slug}`)}><Text style={styles.viewText}>View shop</Text></Pressable><Pressable style={styles.unfollowButton} disabled={busyId === store.id} onPress={() => unfollow(item)}><Text style={styles.unfollowText}>Unfollow</Text></Pressable></View></View></View>; }} />}</View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.bgSecondary }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, list: { padding: spacing.md, gap: spacing.md, paddingBottom: spacing.xxl }, empty: { flexGrow: 1 }, card: { borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.white }, banner: { width: '100%', height: 108 }, bannerFallback: { backgroundColor: colors.bgGreenLight }, body: { padding: spacing.md, gap: spacing.sm }, name: { ...typography.h3, color: colors.textPrimary }, location: { ...typography.caption, color: colors.textMuted }, description: { ...typography.body, color: colors.textSecondary }, stats: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, stat: { ...typography.caption, color: colors.textMuted, marginRight: spacing.sm }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs }, iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: radius.base, backgroundColor: colors.gray50 }, viewButton: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: radius.base, backgroundColor: colors.primary }, viewText: { ...typography.caption, color: colors.white, fontFamily: fontFamily.semiBold }, unfollowButton: { paddingHorizontal: spacing.md, alignItems: 'center', justifyContent: 'center', borderRadius: radius.base, backgroundColor: '#fef2f2' }, unfollowText: { ...typography.caption, color: colors.error }, });
