// Mirrors web/src/config/api.js — grows incrementally as each phase is implemented.
export const ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH_TOKEN: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    PROFILE: '/auth/profile',
  },
  MUNICIPALITIES: '/municipalities',
  QR_LOGIN: {
    SCAN: '/auth/qr/scan',
    APPROVE: '/auth/qr/approve',
  },
  ADDRESSES: {
    LIST: '/addresses',
    CREATE: '/addresses',
    UPDATE: (id) => `/addresses/${id}`,
    DELETE: (id) => `/addresses/${id}`,
    SET_DEFAULT: (id) => `/addresses/${id}/default`,
  },
  CATEGORIES: '/categories',
  PRODUCTS: '/products',
  MY_PRODUCTS: '/products/my/products',
  PRODUCT_BY_ID: (id) => `/products/${id}`,
  PRODUCT_BY_SLUG: (slug) => `/products/slug/${slug}`,
  PRODUCT_IMAGE_SEARCH: '/products/search-by-image',
  STORES: {
    LIST: '/stores',
    BY_ID: (id) => `/stores/${id}`,
    BY_SLUG: (slug) => `/stores/slug/${slug}`,
    STOREFRONT: (slug) => `/stores/slug/${slug}/storefront`,
    COVERAGE: (id) => `/stores/${id}/coverage`,
  },
  FOLLOWS: {
    FOLLOW: (storeId) => `/follows/${storeId}`,
    STATUS: (storeId) => `/follows/status/${storeId}`,
    MINE: '/follows/me',
    NOTIFICATIONS: (storeId) => `/follows/${storeId}/notifications`,
    SELLER_STATS: (storeId) => `/follows/store/${storeId}/stats`,
  },
  REVIEWS: {
    BY_PRODUCT: (productId) => `/reviews/product/${productId}`,
    CREATE: '/reviews',
    MY_REVIEWS: '/reviews/my/reviews',
    BY_ID: (id) => `/reviews/${id}`,
    SELLER_MINE: '/reviews/seller/mine',
    REPLY: (id) => `/reviews/${id}/reply`,
  },
  UPLOAD: {
    IMAGE: '/upload/image',
  },
  ORDERS: {
    CREATE: '/orders',
    MY_ORDERS: '/orders/my/orders',
    BY_ID: (id) => `/orders/${id}`,
    CANCEL: (id) => `/orders/${id}/cancel`,
    STORE_ORDERS: '/orders/store/orders',
    UPDATE_STATUS: (id) => `/orders/${id}/status`,
  },
  SELLER: {
    APPLICATION: '/auth/apply-seller',
    MY_STORE: '/stores/my/store',
    ANALYTICS: '/analytics/seller',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread/count',
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE: (id) => `/notifications/${id}`,
  },
  MESSAGES: {
    CONVERSATIONS: '/messages/conversations',
    CONVERSATION: (id) => `/messages/conversations/${id}`,
    SEND: (id) => `/messages/conversations/${id}/messages`,
    MARK_READ: (id) => `/messages/conversations/${id}/read`,
    RATE_SERVICE: (id) => `/messages/conversations/${id}/rate-service`,
  },
};
